// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// Product is an object representing the database table.
type Product struct {
	ID            int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name          string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Model         string      `boil:"model" json:"model" toml:"model" yaml:"model"`
	Sku           string      `boil:"sku" json:"sku" toml:"sku" yaml:"sku"`
	Location      string      `boil:"location" json:"location" toml:"location" yaml:"location"`
	Quantity      int         `boil:"quantity" json:"quantity" toml:"quantity" yaml:"quantity"`
	Image         null.String `boil:"image" json:"image,omitempty" toml:"image" yaml:"image,omitempty"`
	SupplierID    int         `boil:"supplier_id" json:"supplier_id" toml:"supplier_id" yaml:"supplier_id"`
	Shipping      int8        `boil:"shipping" json:"shipping" toml:"shipping" yaml:"shipping"`
	LastCost      float64     `boil:"last_cost" json:"last_cost" toml:"last_cost" yaml:"last_cost"`
	TaxClassID    int         `boil:"tax_class_id" json:"tax_class_id" toml:"tax_class_id" yaml:"tax_class_id"`
	Weight        float64     `boil:"weight" json:"weight" toml:"weight" yaml:"weight"`
	WeightClassID int         `boil:"weight_class_id" json:"weight_class_id" toml:"weight_class_id" yaml:"weight_class_id"`
	Length        float64     `boil:"length" json:"length" toml:"length" yaml:"length"`
	Width         float64     `boil:"width" json:"width" toml:"width" yaml:"width"`
	Height        float64     `boil:"height" json:"height" toml:"height" yaml:"height"`
	LengthClassID int         `boil:"length_class_id" json:"length_class_id" toml:"length_class_id" yaml:"length_class_id"`
	Subtract      int8        `boil:"subtract" json:"subtract" toml:"subtract" yaml:"subtract"`
	Minimum       int         `boil:"minimum" json:"minimum" toml:"minimum" yaml:"minimum"`
	Status        string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt     null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *productR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L productL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// productR is where relationships are stored.
type productR struct {
	LengthClass *LengthClass
	Supplier    *Supplier
	TaxClass    *TaxClass
	WeightClass *WeightClass
}

// productL is where Load methods for each relationship are stored.
type productL struct{}

var (
	productColumns               = []string{"id", "name", "model", "sku", "location", "quantity", "image", "supplier_id", "shipping", "last_cost", "tax_class_id", "weight", "weight_class_id", "length", "width", "height", "length_class_id", "subtract", "minimum", "status", "created_at", "updated_at", "deleted_at"}
	productColumnsWithoutDefault = []string{"name", "model", "sku", "location", "image", "supplier_id", "tax_class_id", "deleted_at"}
	productColumnsWithDefault    = []string{"id", "quantity", "shipping", "last_cost", "weight", "weight_class_id", "length", "width", "height", "length_class_id", "subtract", "minimum", "status", "created_at", "updated_at"}
	productPrimaryKeyColumns     = []string{"id"}
)

type (
	// ProductSlice is an alias for a slice of pointers to Product.
	// This should generally be used opposed to []Product.
	ProductSlice []*Product
	// ProductHook is the signature for custom Product hook methods
	ProductHook func(boil.Executor, *Product) error

	productQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	productType                 = reflect.TypeOf(&Product{})
	productMapping              = queries.MakeStructMapping(productType)
	productPrimaryKeyMapping, _ = queries.BindMapping(productType, productMapping, productPrimaryKeyColumns)
	productInsertCacheMut       sync.RWMutex
	productInsertCache          = make(map[string]insertCache)
	productUpdateCacheMut       sync.RWMutex
	productUpdateCache          = make(map[string]updateCache)
	productUpsertCacheMut       sync.RWMutex
	productUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var productBeforeInsertHooks []ProductHook
var productBeforeUpdateHooks []ProductHook
var productBeforeDeleteHooks []ProductHook
var productBeforeUpsertHooks []ProductHook

var productAfterInsertHooks []ProductHook
var productAfterSelectHooks []ProductHook
var productAfterUpdateHooks []ProductHook
var productAfterDeleteHooks []ProductHook
var productAfterUpsertHooks []ProductHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Product) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range productBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Product) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range productBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Product) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range productBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Product) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range productBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Product) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range productAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Product) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range productAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Product) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range productAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Product) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range productAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Product) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range productAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProductHook registers your hook function for all future operations.
func AddProductHook(hookPoint boil.HookPoint, productHook ProductHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		productBeforeInsertHooks = append(productBeforeInsertHooks, productHook)
	case boil.BeforeUpdateHook:
		productBeforeUpdateHooks = append(productBeforeUpdateHooks, productHook)
	case boil.BeforeDeleteHook:
		productBeforeDeleteHooks = append(productBeforeDeleteHooks, productHook)
	case boil.BeforeUpsertHook:
		productBeforeUpsertHooks = append(productBeforeUpsertHooks, productHook)
	case boil.AfterInsertHook:
		productAfterInsertHooks = append(productAfterInsertHooks, productHook)
	case boil.AfterSelectHook:
		productAfterSelectHooks = append(productAfterSelectHooks, productHook)
	case boil.AfterUpdateHook:
		productAfterUpdateHooks = append(productAfterUpdateHooks, productHook)
	case boil.AfterDeleteHook:
		productAfterDeleteHooks = append(productAfterDeleteHooks, productHook)
	case boil.AfterUpsertHook:
		productAfterUpsertHooks = append(productAfterUpsertHooks, productHook)
	}
}

// OneP returns a single product record from the query, and panics on error.
func (q productQuery) OneP() *Product {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single product record from the query.
func (q productQuery) One() (*Product, error) {
	o := &Product{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for product")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Product records from the query, and panics on error.
func (q productQuery) AllP() ProductSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Product records from the query.
func (q productQuery) All() (ProductSlice, error) {
	var o []*Product

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Product slice")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Product records in the query, and panics on error.
func (q productQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Product records in the query.
func (q productQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count product rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q productQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q productQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if product exists")
	}

	return count > 0, nil
}

// LengthClassG pointed to by the foreign key.
func (o *Product) LengthClassG(mods ...qm.QueryMod) lengthClassQuery {
	return o.LengthClass(boil.GetDB(), mods...)
}

// LengthClass pointed to by the foreign key.
func (o *Product) LengthClass(exec boil.Executor, mods ...qm.QueryMod) lengthClassQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.LengthClassID),
	}

	queryMods = append(queryMods, mods...)

	query := LengthClasses(exec, queryMods...)
	queries.SetFrom(query.Query, "`length_class`")

	return query
}

// SupplierG pointed to by the foreign key.
func (o *Product) SupplierG(mods ...qm.QueryMod) supplierQuery {
	return o.Supplier(boil.GetDB(), mods...)
}

// Supplier pointed to by the foreign key.
func (o *Product) Supplier(exec boil.Executor, mods ...qm.QueryMod) supplierQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.SupplierID),
	}

	queryMods = append(queryMods, mods...)

	query := Suppliers(exec, queryMods...)
	queries.SetFrom(query.Query, "`supplier`")

	return query
}

// TaxClassG pointed to by the foreign key.
func (o *Product) TaxClassG(mods ...qm.QueryMod) taxClassQuery {
	return o.TaxClass(boil.GetDB(), mods...)
}

// TaxClass pointed to by the foreign key.
func (o *Product) TaxClass(exec boil.Executor, mods ...qm.QueryMod) taxClassQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.TaxClassID),
	}

	queryMods = append(queryMods, mods...)

	query := TaxClasses(exec, queryMods...)
	queries.SetFrom(query.Query, "`tax_class`")

	return query
}

// WeightClassG pointed to by the foreign key.
func (o *Product) WeightClassG(mods ...qm.QueryMod) weightClassQuery {
	return o.WeightClass(boil.GetDB(), mods...)
}

// WeightClass pointed to by the foreign key.
func (o *Product) WeightClass(exec boil.Executor, mods ...qm.QueryMod) weightClassQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.WeightClassID),
	}

	queryMods = append(queryMods, mods...)

	query := WeightClasses(exec, queryMods...)
	queries.SetFrom(query.Query, "`weight_class`")

	return query
} // LoadLengthClass allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (productL) LoadLengthClass(e boil.Executor, singular bool, maybeProduct interface{}) error {
	var slice []*Product
	var object *Product

	count := 1
	if singular {
		object = maybeProduct.(*Product)
	} else {
		slice = *maybeProduct.(*[]*Product)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &productR{}
		}
		args[0] = object.LengthClassID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &productR{}
			}
			args[i] = obj.LengthClassID
		}
	}

	query := fmt.Sprintf(
		"select * from `length_class` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load LengthClass")
	}
	defer results.Close()

	var resultSlice []*LengthClass
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice LengthClass")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.LengthClass = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LengthClassID == foreign.ID {
				local.R.LengthClass = foreign
				break
			}
		}
	}

	return nil
}

// LoadSupplier allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (productL) LoadSupplier(e boil.Executor, singular bool, maybeProduct interface{}) error {
	var slice []*Product
	var object *Product

	count := 1
	if singular {
		object = maybeProduct.(*Product)
	} else {
		slice = *maybeProduct.(*[]*Product)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &productR{}
		}
		args[0] = object.SupplierID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &productR{}
			}
			args[i] = obj.SupplierID
		}
	}

	query := fmt.Sprintf(
		"select * from `supplier` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Supplier")
	}
	defer results.Close()

	var resultSlice []*Supplier
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Supplier")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Supplier = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SupplierID == foreign.ID {
				local.R.Supplier = foreign
				break
			}
		}
	}

	return nil
}

// LoadTaxClass allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (productL) LoadTaxClass(e boil.Executor, singular bool, maybeProduct interface{}) error {
	var slice []*Product
	var object *Product

	count := 1
	if singular {
		object = maybeProduct.(*Product)
	} else {
		slice = *maybeProduct.(*[]*Product)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &productR{}
		}
		args[0] = object.TaxClassID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &productR{}
			}
			args[i] = obj.TaxClassID
		}
	}

	query := fmt.Sprintf(
		"select * from `tax_class` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TaxClass")
	}
	defer results.Close()

	var resultSlice []*TaxClass
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TaxClass")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.TaxClass = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TaxClassID == foreign.ID {
				local.R.TaxClass = foreign
				break
			}
		}
	}

	return nil
}

// LoadWeightClass allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (productL) LoadWeightClass(e boil.Executor, singular bool, maybeProduct interface{}) error {
	var slice []*Product
	var object *Product

	count := 1
	if singular {
		object = maybeProduct.(*Product)
	} else {
		slice = *maybeProduct.(*[]*Product)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &productR{}
		}
		args[0] = object.WeightClassID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &productR{}
			}
			args[i] = obj.WeightClassID
		}
	}

	query := fmt.Sprintf(
		"select * from `weight_class` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load WeightClass")
	}
	defer results.Close()

	var resultSlice []*WeightClass
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice WeightClass")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.WeightClass = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WeightClassID == foreign.ID {
				local.R.WeightClass = foreign
				break
			}
		}
	}

	return nil
}

// SetLengthClassG of the product to the related item.
// Sets o.R.LengthClass to related.
// Adds o to related.R.Products.
// Uses the global database handle.
func (o *Product) SetLengthClassG(insert bool, related *LengthClass) error {
	return o.SetLengthClass(boil.GetDB(), insert, related)
}

// SetLengthClassP of the product to the related item.
// Sets o.R.LengthClass to related.
// Adds o to related.R.Products.
// Panics on error.
func (o *Product) SetLengthClassP(exec boil.Executor, insert bool, related *LengthClass) {
	if err := o.SetLengthClass(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetLengthClassGP of the product to the related item.
// Sets o.R.LengthClass to related.
// Adds o to related.R.Products.
// Uses the global database handle and panics on error.
func (o *Product) SetLengthClassGP(insert bool, related *LengthClass) {
	if err := o.SetLengthClass(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetLengthClass of the product to the related item.
// Sets o.R.LengthClass to related.
// Adds o to related.R.Products.
func (o *Product) SetLengthClass(exec boil.Executor, insert bool, related *LengthClass) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `product` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"length_class_id"}),
		strmangle.WhereClause("`", "`", 0, productPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LengthClassID = related.ID

	if o.R == nil {
		o.R = &productR{
			LengthClass: related,
		}
	} else {
		o.R.LengthClass = related
	}

	if related.R == nil {
		related.R = &lengthClassR{
			Products: ProductSlice{o},
		}
	} else {
		related.R.Products = append(related.R.Products, o)
	}

	return nil
}

// SetSupplierG of the product to the related item.
// Sets o.R.Supplier to related.
// Adds o to related.R.Products.
// Uses the global database handle.
func (o *Product) SetSupplierG(insert bool, related *Supplier) error {
	return o.SetSupplier(boil.GetDB(), insert, related)
}

// SetSupplierP of the product to the related item.
// Sets o.R.Supplier to related.
// Adds o to related.R.Products.
// Panics on error.
func (o *Product) SetSupplierP(exec boil.Executor, insert bool, related *Supplier) {
	if err := o.SetSupplier(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetSupplierGP of the product to the related item.
// Sets o.R.Supplier to related.
// Adds o to related.R.Products.
// Uses the global database handle and panics on error.
func (o *Product) SetSupplierGP(insert bool, related *Supplier) {
	if err := o.SetSupplier(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetSupplier of the product to the related item.
// Sets o.R.Supplier to related.
// Adds o to related.R.Products.
func (o *Product) SetSupplier(exec boil.Executor, insert bool, related *Supplier) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `product` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"supplier_id"}),
		strmangle.WhereClause("`", "`", 0, productPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SupplierID = related.ID

	if o.R == nil {
		o.R = &productR{
			Supplier: related,
		}
	} else {
		o.R.Supplier = related
	}

	if related.R == nil {
		related.R = &supplierR{
			Products: ProductSlice{o},
		}
	} else {
		related.R.Products = append(related.R.Products, o)
	}

	return nil
}

// SetTaxClassG of the product to the related item.
// Sets o.R.TaxClass to related.
// Adds o to related.R.Products.
// Uses the global database handle.
func (o *Product) SetTaxClassG(insert bool, related *TaxClass) error {
	return o.SetTaxClass(boil.GetDB(), insert, related)
}

// SetTaxClassP of the product to the related item.
// Sets o.R.TaxClass to related.
// Adds o to related.R.Products.
// Panics on error.
func (o *Product) SetTaxClassP(exec boil.Executor, insert bool, related *TaxClass) {
	if err := o.SetTaxClass(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTaxClassGP of the product to the related item.
// Sets o.R.TaxClass to related.
// Adds o to related.R.Products.
// Uses the global database handle and panics on error.
func (o *Product) SetTaxClassGP(insert bool, related *TaxClass) {
	if err := o.SetTaxClass(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTaxClass of the product to the related item.
// Sets o.R.TaxClass to related.
// Adds o to related.R.Products.
func (o *Product) SetTaxClass(exec boil.Executor, insert bool, related *TaxClass) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `product` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"tax_class_id"}),
		strmangle.WhereClause("`", "`", 0, productPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TaxClassID = related.ID

	if o.R == nil {
		o.R = &productR{
			TaxClass: related,
		}
	} else {
		o.R.TaxClass = related
	}

	if related.R == nil {
		related.R = &taxClassR{
			Products: ProductSlice{o},
		}
	} else {
		related.R.Products = append(related.R.Products, o)
	}

	return nil
}

// SetWeightClassG of the product to the related item.
// Sets o.R.WeightClass to related.
// Adds o to related.R.Products.
// Uses the global database handle.
func (o *Product) SetWeightClassG(insert bool, related *WeightClass) error {
	return o.SetWeightClass(boil.GetDB(), insert, related)
}

// SetWeightClassP of the product to the related item.
// Sets o.R.WeightClass to related.
// Adds o to related.R.Products.
// Panics on error.
func (o *Product) SetWeightClassP(exec boil.Executor, insert bool, related *WeightClass) {
	if err := o.SetWeightClass(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetWeightClassGP of the product to the related item.
// Sets o.R.WeightClass to related.
// Adds o to related.R.Products.
// Uses the global database handle and panics on error.
func (o *Product) SetWeightClassGP(insert bool, related *WeightClass) {
	if err := o.SetWeightClass(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetWeightClass of the product to the related item.
// Sets o.R.WeightClass to related.
// Adds o to related.R.Products.
func (o *Product) SetWeightClass(exec boil.Executor, insert bool, related *WeightClass) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `product` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"weight_class_id"}),
		strmangle.WhereClause("`", "`", 0, productPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WeightClassID = related.ID

	if o.R == nil {
		o.R = &productR{
			WeightClass: related,
		}
	} else {
		o.R.WeightClass = related
	}

	if related.R == nil {
		related.R = &weightClassR{
			Products: ProductSlice{o},
		}
	} else {
		related.R.Products = append(related.R.Products, o)
	}

	return nil
}

// ProductsG retrieves all records.
func ProductsG(mods ...qm.QueryMod) productQuery {
	return Products(boil.GetDB(), mods...)
}

// Products retrieves all the records using an executor.
func Products(exec boil.Executor, mods ...qm.QueryMod) productQuery {
	mods = append(mods, qm.From("`product`"))
	return productQuery{NewQuery(exec, mods...)}
}

// FindProductG retrieves a single record by ID.
func FindProductG(id int, selectCols ...string) (*Product, error) {
	return FindProduct(boil.GetDB(), id, selectCols...)
}

// FindProductGP retrieves a single record by ID, and panics on error.
func FindProductGP(id int, selectCols ...string) *Product {
	retobj, err := FindProduct(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindProduct retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProduct(exec boil.Executor, id int, selectCols ...string) (*Product, error) {
	productObj := &Product{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `product` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(productObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from product")
	}

	return productObj, nil
}

// FindProductP retrieves a single record by ID with an executor, and panics on error.
func FindProductP(exec boil.Executor, id int, selectCols ...string) *Product {
	retobj, err := FindProduct(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Product) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Product) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Product) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Product) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no product provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(productColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	productInsertCacheMut.RLock()
	cache, cached := productInsertCache[key]
	productInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			productColumns,
			productColumnsWithDefault,
			productColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(productType, productMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(productType, productMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `product` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `product` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `product` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, productPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into product")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == productMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for product")
	}

CacheNoHooks:
	if !cached {
		productInsertCacheMut.Lock()
		productInsertCache[key] = cache
		productInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Product record. See Update for
// whitelist behavior description.
func (o *Product) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Product record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Product) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Product, and panics on error.
// See Update for whitelist behavior description.
func (o *Product) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Product.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Product) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	productUpdateCacheMut.RLock()
	cache, cached := productUpdateCache[key]
	productUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			productColumns,
			productPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update product, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `product` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, productPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(productType, productMapping, append(wl, productPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update product row")
	}

	if !cached {
		productUpdateCacheMut.Lock()
		productUpdateCache[key] = cache
		productUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q productQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q productQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for product")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ProductSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o ProductSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o ProductSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProductSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `product` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, productPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in product slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Product) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Product) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Product) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Product) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no product provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(productColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	productUpsertCacheMut.RLock()
	cache, cached := productUpsertCache[key]
	productUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			productColumns,
			productColumnsWithDefault,
			productColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			productColumns,
			productPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert product, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "product", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `product` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(productType, productMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(productType, productMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for product")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == productMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for product")
	}

CacheNoHooks:
	if !cached {
		productUpsertCacheMut.Lock()
		productUpsertCache[key] = cache
		productUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Product record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Product) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Product record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Product) DeleteG() error {
	if o == nil {
		return errors.New("models: no Product provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Product record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Product) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Product record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Product) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Product provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), productPrimaryKeyMapping)
	sql := "DELETE FROM `product` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from product")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q productQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q productQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no productQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from product")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o ProductSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o ProductSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Product slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o ProductSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProductSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Product slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(productBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `product` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, productPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from product slice")
	}

	if len(productAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Product) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Product) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Product) ReloadG() error {
	if o == nil {
		return errors.New("models: no Product provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Product) Reload(exec boil.Executor) error {
	ret, err := FindProduct(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ProductSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ProductSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProductSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty ProductSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProductSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	products := ProductSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `product`.* FROM `product` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, productPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&products)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ProductSlice")
	}

	*o = products

	return nil
}

// ProductExists checks if the Product row exists.
func ProductExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `product` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if product exists")
	}

	return exists, nil
}

// ProductExistsG checks if the Product row exists.
func ProductExistsG(id int) (bool, error) {
	return ProductExists(boil.GetDB(), id)
}

// ProductExistsGP checks if the Product row exists. Panics on error.
func ProductExistsGP(id int) bool {
	e, err := ProductExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ProductExistsP checks if the Product row exists. Panics on error.
func ProductExistsP(exec boil.Executor, id int) bool {
	e, err := ProductExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
