// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/randomize"
	"github.com/vattle/sqlboiler/strmangle"
)

func testProducts(t *testing.T) {
	t.Parallel()

	query := Products(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testProductsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = product.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Products(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := ProductSlice{product}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testProductsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := ProductExists(tx, product.ID)
	if err != nil {
		t.Errorf("Unable to check if Product exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ProductExistsG to return true, but got false.")
	}
}
func testProductsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	productFound, err := FindProduct(tx, product.ID)
	if err != nil {
		t.Error(err)
	}

	if productFound == nil {
		t.Error("want a record, got nil")
	}
}
func testProductsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Products(tx).Bind(product); err != nil {
		t.Error(err)
	}
}

func testProductsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := Products(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testProductsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	productOne := &Product{}
	productTwo := &Product{}
	if err = randomize.Struct(seed, productOne, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}
	if err = randomize.Struct(seed, productTwo, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = productOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = productTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Products(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testProductsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	productOne := &Product{}
	productTwo := &Product{}
	if err = randomize.Struct(seed, productOne, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}
	if err = randomize.Struct(seed, productTwo, productDBTypes, false, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = productOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = productTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func productBeforeInsertHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func productAfterInsertHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func productAfterSelectHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func productBeforeUpdateHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func productAfterUpdateHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func productBeforeDeleteHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func productAfterDeleteHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func productBeforeUpsertHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func productAfterUpsertHook(e boil.Executor, o *Product) error {
	*o = Product{}
	return nil
}

func testProductsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &Product{}
	o := &Product{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, productDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Product object: %s", err)
	}

	AddProductHook(boil.BeforeInsertHook, productBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	productBeforeInsertHooks = []ProductHook{}

	AddProductHook(boil.AfterInsertHook, productAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	productAfterInsertHooks = []ProductHook{}

	AddProductHook(boil.AfterSelectHook, productAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	productAfterSelectHooks = []ProductHook{}

	AddProductHook(boil.BeforeUpdateHook, productBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	productBeforeUpdateHooks = []ProductHook{}

	AddProductHook(boil.AfterUpdateHook, productAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	productAfterUpdateHooks = []ProductHook{}

	AddProductHook(boil.BeforeDeleteHook, productBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	productBeforeDeleteHooks = []ProductHook{}

	AddProductHook(boil.AfterDeleteHook, productAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	productAfterDeleteHooks = []ProductHook{}

	AddProductHook(boil.BeforeUpsertHook, productBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	productBeforeUpsertHooks = []ProductHook{}

	AddProductHook(boil.AfterUpsertHook, productAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	productAfterUpsertHooks = []ProductHook{}
}
func testProductsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProductsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx, productColumnsWithoutDefault...); err != nil {
		t.Error(err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProductToOneLengthClassUsingLengthClass(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local Product
	var foreign LengthClass

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, lengthClassDBTypes, true, lengthClassColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LengthClass struct: %s", err)
	}

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.LengthClassID = foreign.ID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.LengthClass(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ProductSlice{&local}
	if err = local.L.LoadLengthClass(tx, false, (*[]*Product)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.LengthClass == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.LengthClass = nil
	if err = local.L.LoadLengthClass(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.LengthClass == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testProductToOneSupplierUsingSupplier(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local Product
	var foreign Supplier

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, supplierDBTypes, true, supplierColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Supplier struct: %s", err)
	}

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.SupplierID = foreign.ID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.Supplier(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ProductSlice{&local}
	if err = local.L.LoadSupplier(tx, false, (*[]*Product)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.Supplier == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Supplier = nil
	if err = local.L.LoadSupplier(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.Supplier == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testProductToOneTaxClassUsingTaxClass(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local Product
	var foreign TaxClass

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, taxClassDBTypes, true, taxClassColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TaxClass struct: %s", err)
	}

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.TaxClassID = foreign.ID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.TaxClass(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ProductSlice{&local}
	if err = local.L.LoadTaxClass(tx, false, (*[]*Product)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.TaxClass == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.TaxClass = nil
	if err = local.L.LoadTaxClass(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.TaxClass == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testProductToOneWeightClassUsingWeightClass(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local Product
	var foreign WeightClass

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, weightClassDBTypes, true, weightClassColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WeightClass struct: %s", err)
	}

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.WeightClassID = foreign.ID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.WeightClass(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ProductSlice{&local}
	if err = local.L.LoadWeightClass(tx, false, (*[]*Product)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.WeightClass == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.WeightClass = nil
	if err = local.L.LoadWeightClass(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.WeightClass == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testProductToOneSetOpLengthClassUsingLengthClass(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Product
	var b, c LengthClass

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, lengthClassDBTypes, false, strmangle.SetComplement(lengthClassPrimaryKeyColumns, lengthClassColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, lengthClassDBTypes, false, strmangle.SetComplement(lengthClassPrimaryKeyColumns, lengthClassColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*LengthClass{&b, &c} {
		err = a.SetLengthClass(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.LengthClass != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Products[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.LengthClassID != x.ID {
			t.Error("foreign key was wrong value", a.LengthClassID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.LengthClassID))
		reflect.Indirect(reflect.ValueOf(&a.LengthClassID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.LengthClassID != x.ID {
			t.Error("foreign key was wrong value", a.LengthClassID, x.ID)
		}
	}
}
func testProductToOneSetOpSupplierUsingSupplier(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Product
	var b, c Supplier

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, supplierDBTypes, false, strmangle.SetComplement(supplierPrimaryKeyColumns, supplierColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, supplierDBTypes, false, strmangle.SetComplement(supplierPrimaryKeyColumns, supplierColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Supplier{&b, &c} {
		err = a.SetSupplier(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Supplier != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Products[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.SupplierID != x.ID {
			t.Error("foreign key was wrong value", a.SupplierID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.SupplierID))
		reflect.Indirect(reflect.ValueOf(&a.SupplierID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.SupplierID != x.ID {
			t.Error("foreign key was wrong value", a.SupplierID, x.ID)
		}
	}
}
func testProductToOneSetOpTaxClassUsingTaxClass(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Product
	var b, c TaxClass

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, taxClassDBTypes, false, strmangle.SetComplement(taxClassPrimaryKeyColumns, taxClassColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, taxClassDBTypes, false, strmangle.SetComplement(taxClassPrimaryKeyColumns, taxClassColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*TaxClass{&b, &c} {
		err = a.SetTaxClass(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.TaxClass != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Products[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TaxClassID != x.ID {
			t.Error("foreign key was wrong value", a.TaxClassID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TaxClassID))
		reflect.Indirect(reflect.ValueOf(&a.TaxClassID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TaxClassID != x.ID {
			t.Error("foreign key was wrong value", a.TaxClassID, x.ID)
		}
	}
}
func testProductToOneSetOpWeightClassUsingWeightClass(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Product
	var b, c WeightClass

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, productDBTypes, false, strmangle.SetComplement(productPrimaryKeyColumns, productColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, weightClassDBTypes, false, strmangle.SetComplement(weightClassPrimaryKeyColumns, weightClassColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, weightClassDBTypes, false, strmangle.SetComplement(weightClassPrimaryKeyColumns, weightClassColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*WeightClass{&b, &c} {
		err = a.SetWeightClass(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.WeightClass != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Products[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.WeightClassID != x.ID {
			t.Error("foreign key was wrong value", a.WeightClassID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WeightClassID))
		reflect.Indirect(reflect.ValueOf(&a.WeightClassID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.WeightClassID != x.ID {
			t.Error("foreign key was wrong value", a.WeightClassID, x.ID)
		}
	}
}
func testProductsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = product.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testProductsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := ProductSlice{product}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testProductsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Products(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	productDBTypes = map[string]string{`CreatedAt`: `timestamp`, `DeletedAt`: `timestamp`, `Height`: `decimal`, `ID`: `int`, `Image`: `varchar`, `LastCostPrice`: `decimal`, `Length`: `decimal`, `LengthClassID`: `int`, `Location`: `varchar`, `Minimum`: `int`, `Model`: `varchar`, `Name`: `varchar`, `Quantity`: `int`, `Shipping`: `tinyint`, `Sku`: `varchar`, `Status`: `enum('enabled','disabled')`, `Subtract`: `tinyint`, `SupplierID`: `int`, `TaxClassID`: `int`, `UpdatedAt`: `timestamp`, `Weight`: `decimal`, `WeightClassID`: `int`, `Width`: `decimal`}
	_              = bytes.MinRead
)

func testProductsUpdate(t *testing.T) {
	t.Parallel()

	if len(productColumns) == len(productPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	if err = product.Update(tx); err != nil {
		t.Error(err)
	}
}

func testProductsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(productColumns) == len(productPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	product := &Product{}
	if err = randomize.Struct(seed, product, productDBTypes, true, productColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, product, productDBTypes, true, productPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(productColumns, productPrimaryKeyColumns) {
		fields = productColumns
	} else {
		fields = strmangle.SetComplement(
			productColumns,
			productPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(product))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := ProductSlice{product}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testProductsUpsert(t *testing.T) {
	t.Parallel()

	if len(productColumns) == len(productPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	product := Product{}
	if err = randomize.Struct(seed, &product, productDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = product.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Product: %s", err)
	}

	count, err := Products(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &product, productDBTypes, false, productPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Product struct: %s", err)
	}

	if err = product.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Product: %s", err)
	}

	count, err = Products(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
