// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
)

// TaxClass is an object representing the database table.
type TaxClass struct {
	ID          int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Title       string    `boil:"title" json:"title" toml:"title" yaml:"title"`
	Description string    `boil:"description" json:"description" toml:"description" yaml:"description"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *taxClassR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L taxClassL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// taxClassR is where relationships are stored.
type taxClassR struct {
	Products ProductSlice
}

// taxClassL is where Load methods for each relationship are stored.
type taxClassL struct{}

var (
	taxClassColumns               = []string{"id", "title", "description", "created_at", "updated_at"}
	taxClassColumnsWithoutDefault = []string{"title", "description"}
	taxClassColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	taxClassPrimaryKeyColumns     = []string{"id"}
)

type (
	// TaxClassSlice is an alias for a slice of pointers to TaxClass.
	// This should generally be used opposed to []TaxClass.
	TaxClassSlice []*TaxClass
	// TaxClassHook is the signature for custom TaxClass hook methods
	TaxClassHook func(boil.Executor, *TaxClass) error

	taxClassQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	taxClassType                 = reflect.TypeOf(&TaxClass{})
	taxClassMapping              = queries.MakeStructMapping(taxClassType)
	taxClassPrimaryKeyMapping, _ = queries.BindMapping(taxClassType, taxClassMapping, taxClassPrimaryKeyColumns)
	taxClassInsertCacheMut       sync.RWMutex
	taxClassInsertCache          = make(map[string]insertCache)
	taxClassUpdateCacheMut       sync.RWMutex
	taxClassUpdateCache          = make(map[string]updateCache)
	taxClassUpsertCacheMut       sync.RWMutex
	taxClassUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var taxClassBeforeInsertHooks []TaxClassHook
var taxClassBeforeUpdateHooks []TaxClassHook
var taxClassBeforeDeleteHooks []TaxClassHook
var taxClassBeforeUpsertHooks []TaxClassHook

var taxClassAfterInsertHooks []TaxClassHook
var taxClassAfterSelectHooks []TaxClassHook
var taxClassAfterUpdateHooks []TaxClassHook
var taxClassAfterDeleteHooks []TaxClassHook
var taxClassAfterUpsertHooks []TaxClassHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TaxClass) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TaxClass) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TaxClass) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TaxClass) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TaxClass) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TaxClass) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TaxClass) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TaxClass) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TaxClass) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range taxClassAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTaxClassHook registers your hook function for all future operations.
func AddTaxClassHook(hookPoint boil.HookPoint, taxClassHook TaxClassHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		taxClassBeforeInsertHooks = append(taxClassBeforeInsertHooks, taxClassHook)
	case boil.BeforeUpdateHook:
		taxClassBeforeUpdateHooks = append(taxClassBeforeUpdateHooks, taxClassHook)
	case boil.BeforeDeleteHook:
		taxClassBeforeDeleteHooks = append(taxClassBeforeDeleteHooks, taxClassHook)
	case boil.BeforeUpsertHook:
		taxClassBeforeUpsertHooks = append(taxClassBeforeUpsertHooks, taxClassHook)
	case boil.AfterInsertHook:
		taxClassAfterInsertHooks = append(taxClassAfterInsertHooks, taxClassHook)
	case boil.AfterSelectHook:
		taxClassAfterSelectHooks = append(taxClassAfterSelectHooks, taxClassHook)
	case boil.AfterUpdateHook:
		taxClassAfterUpdateHooks = append(taxClassAfterUpdateHooks, taxClassHook)
	case boil.AfterDeleteHook:
		taxClassAfterDeleteHooks = append(taxClassAfterDeleteHooks, taxClassHook)
	case boil.AfterUpsertHook:
		taxClassAfterUpsertHooks = append(taxClassAfterUpsertHooks, taxClassHook)
	}
}

// OneP returns a single taxClass record from the query, and panics on error.
func (q taxClassQuery) OneP() *TaxClass {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single taxClass record from the query.
func (q taxClassQuery) One() (*TaxClass, error) {
	o := &TaxClass{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for tax_class")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all TaxClass records from the query, and panics on error.
func (q taxClassQuery) AllP() TaxClassSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all TaxClass records from the query.
func (q taxClassQuery) All() (TaxClassSlice, error) {
	var o []*TaxClass

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TaxClass slice")
	}

	if len(taxClassAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all TaxClass records in the query, and panics on error.
func (q taxClassQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all TaxClass records in the query.
func (q taxClassQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count tax_class rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q taxClassQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q taxClassQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if tax_class exists")
	}

	return count > 0, nil
}

// ProductsG retrieves all the product's product.
func (o *TaxClass) ProductsG(mods ...qm.QueryMod) productQuery {
	return o.Products(boil.GetDB(), mods...)
}

// Products retrieves all the product's product with an executor.
func (o *TaxClass) Products(exec boil.Executor, mods ...qm.QueryMod) productQuery {
	queryMods := []qm.QueryMod{
		qm.Select("`a`.*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`a`.`tax_class_id`=?", o.ID),
	)

	query := Products(exec, queryMods...)
	queries.SetFrom(query.Query, "`product` as `a`")
	return query
}

// LoadProducts allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (taxClassL) LoadProducts(e boil.Executor, singular bool, maybeTaxClass interface{}) error {
	var slice []*TaxClass
	var object *TaxClass

	count := 1
	if singular {
		object = maybeTaxClass.(*TaxClass)
	} else {
		slice = *maybeTaxClass.(*[]*TaxClass)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &taxClassR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &taxClassR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from `product` where `tax_class_id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load product")
	}
	defer results.Close()

	var resultSlice []*Product
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice product")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Products = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TaxClassID {
				local.R.Products = append(local.R.Products, foreign)
				break
			}
		}
	}

	return nil
}

// AddProductsG adds the given related objects to the existing relationships
// of the tax_class, optionally inserting them as new records.
// Appends related to o.R.Products.
// Sets related.R.TaxClass appropriately.
// Uses the global database handle.
func (o *TaxClass) AddProductsG(insert bool, related ...*Product) error {
	return o.AddProducts(boil.GetDB(), insert, related...)
}

// AddProductsP adds the given related objects to the existing relationships
// of the tax_class, optionally inserting them as new records.
// Appends related to o.R.Products.
// Sets related.R.TaxClass appropriately.
// Panics on error.
func (o *TaxClass) AddProductsP(exec boil.Executor, insert bool, related ...*Product) {
	if err := o.AddProducts(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddProductsGP adds the given related objects to the existing relationships
// of the tax_class, optionally inserting them as new records.
// Appends related to o.R.Products.
// Sets related.R.TaxClass appropriately.
// Uses the global database handle and panics on error.
func (o *TaxClass) AddProductsGP(insert bool, related ...*Product) {
	if err := o.AddProducts(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddProducts adds the given related objects to the existing relationships
// of the tax_class, optionally inserting them as new records.
// Appends related to o.R.Products.
// Sets related.R.TaxClass appropriately.
func (o *TaxClass) AddProducts(exec boil.Executor, insert bool, related ...*Product) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TaxClassID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `product` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"tax_class_id"}),
				strmangle.WhereClause("`", "`", 0, productPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TaxClassID = o.ID
		}
	}

	if o.R == nil {
		o.R = &taxClassR{
			Products: related,
		}
	} else {
		o.R.Products = append(o.R.Products, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &productR{
				TaxClass: o,
			}
		} else {
			rel.R.TaxClass = o
		}
	}
	return nil
}

// TaxClassesG retrieves all records.
func TaxClassesG(mods ...qm.QueryMod) taxClassQuery {
	return TaxClasses(boil.GetDB(), mods...)
}

// TaxClasses retrieves all the records using an executor.
func TaxClasses(exec boil.Executor, mods ...qm.QueryMod) taxClassQuery {
	mods = append(mods, qm.From("`tax_class`"))
	return taxClassQuery{NewQuery(exec, mods...)}
}

// FindTaxClassG retrieves a single record by ID.
func FindTaxClassG(id int, selectCols ...string) (*TaxClass, error) {
	return FindTaxClass(boil.GetDB(), id, selectCols...)
}

// FindTaxClassGP retrieves a single record by ID, and panics on error.
func FindTaxClassGP(id int, selectCols ...string) *TaxClass {
	retobj, err := FindTaxClass(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindTaxClass retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTaxClass(exec boil.Executor, id int, selectCols ...string) (*TaxClass, error) {
	taxClassObj := &TaxClass{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `tax_class` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(taxClassObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from tax_class")
	}

	return taxClassObj, nil
}

// FindTaxClassP retrieves a single record by ID with an executor, and panics on error.
func FindTaxClassP(exec boil.Executor, id int, selectCols ...string) *TaxClass {
	retobj, err := FindTaxClass(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *TaxClass) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *TaxClass) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *TaxClass) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *TaxClass) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no tax_class provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(taxClassColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	taxClassInsertCacheMut.RLock()
	cache, cached := taxClassInsertCache[key]
	taxClassInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			taxClassColumns,
			taxClassColumnsWithDefault,
			taxClassColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(taxClassType, taxClassMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(taxClassType, taxClassMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `tax_class` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `tax_class` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `tax_class` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, taxClassPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into tax_class")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == taxClassMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for tax_class")
	}

CacheNoHooks:
	if !cached {
		taxClassInsertCacheMut.Lock()
		taxClassInsertCache[key] = cache
		taxClassInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single TaxClass record. See Update for
// whitelist behavior description.
func (o *TaxClass) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single TaxClass record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *TaxClass) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the TaxClass, and panics on error.
// See Update for whitelist behavior description.
func (o *TaxClass) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the TaxClass.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *TaxClass) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	taxClassUpdateCacheMut.RLock()
	cache, cached := taxClassUpdateCache[key]
	taxClassUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			taxClassColumns,
			taxClassPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update tax_class, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `tax_class` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, taxClassPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(taxClassType, taxClassMapping, append(wl, taxClassPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update tax_class row")
	}

	if !cached {
		taxClassUpdateCacheMut.Lock()
		taxClassUpdateCache[key] = cache
		taxClassUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q taxClassQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q taxClassQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for tax_class")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TaxClassSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o TaxClassSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o TaxClassSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TaxClassSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), taxClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `tax_class` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, taxClassPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in taxClass slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *TaxClass) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *TaxClass) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *TaxClass) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *TaxClass) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no tax_class provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(taxClassColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	taxClassUpsertCacheMut.RLock()
	cache, cached := taxClassUpsertCache[key]
	taxClassUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			taxClassColumns,
			taxClassColumnsWithDefault,
			taxClassColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			taxClassColumns,
			taxClassPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert tax_class, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "tax_class", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `tax_class` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(taxClassType, taxClassMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(taxClassType, taxClassMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for tax_class")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == taxClassMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for tax_class")
	}

CacheNoHooks:
	if !cached {
		taxClassUpsertCacheMut.Lock()
		taxClassUpsertCache[key] = cache
		taxClassUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single TaxClass record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *TaxClass) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single TaxClass record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *TaxClass) DeleteG() error {
	if o == nil {
		return errors.New("models: no TaxClass provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single TaxClass record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *TaxClass) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single TaxClass record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TaxClass) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no TaxClass provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), taxClassPrimaryKeyMapping)
	sql := "DELETE FROM `tax_class` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from tax_class")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q taxClassQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q taxClassQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no taxClassQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from tax_class")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o TaxClassSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o TaxClassSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no TaxClass slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o TaxClassSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TaxClassSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no TaxClass slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(taxClassBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), taxClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `tax_class` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, taxClassPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from taxClass slice")
	}

	if len(taxClassAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *TaxClass) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *TaxClass) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *TaxClass) ReloadG() error {
	if o == nil {
		return errors.New("models: no TaxClass provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TaxClass) Reload(exec boil.Executor) error {
	ret, err := FindTaxClass(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TaxClassSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *TaxClassSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TaxClassSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty TaxClassSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TaxClassSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	taxClasses := TaxClassSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), taxClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `tax_class`.* FROM `tax_class` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, taxClassPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&taxClasses)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TaxClassSlice")
	}

	*o = taxClasses

	return nil
}

// TaxClassExists checks if the TaxClass row exists.
func TaxClassExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `tax_class` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if tax_class exists")
	}

	return exists, nil
}

// TaxClassExistsG checks if the TaxClass row exists.
func TaxClassExistsG(id int) (bool, error) {
	return TaxClassExists(boil.GetDB(), id)
}

// TaxClassExistsGP checks if the TaxClass row exists. Panics on error.
func TaxClassExistsGP(id int) bool {
	e, err := TaxClassExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// TaxClassExistsP checks if the TaxClass row exists. Panics on error.
func TaxClassExistsP(exec boil.Executor, id int) bool {
	e, err := TaxClassExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
